packages:
  - frontend
  - hono
  - media
  - remark

# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'markuplint'
  - 'stylelint'

## Build Settings

strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
