packages:
  - frontend
  - hono
  - remark

# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
trustPolicyExclude:
  - chokidar@4.0.3
  - semver@6.3.1
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'stylelint'

## Build Settings

strictDepBuilds: true
onlyBuiltDependencies:
  - better-sqlite3
  - esbuild
