packages:
  - frontend
  - hono
  - media
  - remark

# Settings <https://pnpm.io/settings>

## Dependency Resolution

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1 # eslint-plugin-import@2.32.0 <https://github.com/import-js/eslint-plugin-import/blob/main/package.json>
blockExoticSubdeps: true

## Dependency Hoisting Settings

publicHoistPattern:
  - 'eslint'
  - 'markuplint'
  - 'stylelint'

## Build Settings

strictDepBuilds: true
allowBuilds:
  better-sqlite3: true
  esbuild: true
  sharp: true
