/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = number;
export type URLOrigin = string;
export type NoName3 = number;
export type URLOrigin1 = string;
export type NoName5 = string;
export type NoName6 = string;
export type NoName7 = string;
export type NoName8 = string;
export type Brotli = string;

export interface NoName {
  maximum_number: NoName1;
  image_external: NoName2;
  view: View;
  html: HTML;
}
export interface NoName2 {
  amazon: Amazon;
  twitter: Twitter;
}
export interface Amazon {
  origin: URLOrigin;
  size: NoName3;
}
export interface Twitter {
  origin: URLOrigin1;
  params: NoName4;
}
export interface NoName4 {
  [k: string]: NoName5;
}
export interface View {
  success: NoName6;
}
export interface HTML {
  directory: NoName7;
  extension: NoName8;
  brotli_extension: Brotli;
}
