/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type NoName2 = string;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type ContentSecurityPolicyHTML1 = string;
export type ContentSecurityPolicyReportOnlyHTML = string;
export type Threshold = string;
export type NoName7 = string;
export type NoName8 = string[];
export type NoName9 = string[];
export type NoName11 = string[];
export type NoName12 = string[];
export type NoName15 = string;
export type NoName17 = string[];
export type NoName18 = string;
export type NoName16 = {
  paths: NoName17;
  value: NoName18;
}[];
export type NoName20 = string[];
export type NoName21 = string;
export type NoName19 = {
  extensions: NoName20;
  value: NoName21;
}[];
export type CORS1 = string[];
export type NoName23 = string[];
export type NoName24 = string[];
export type Directory = string[];
export type NoName25 = string;
export type Htpasswd = string;
export type BasicAuthentication = {
  directory: Directory;
  realm: NoName25;
  htpasswd: Htpasswd;
}[];
export type NoName26 = string;
export type NoName27 = string;
export type FilepathFor401Unauthorized = string;
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type FilepathFor500InternalServerError = string;
export type NoName29 = string;
export type NoName31 = string;
export type Blog = string;
export type NoName32 = string;
export type NoName35 = number;

export interface NoName {
  port: HTTP;
  request: NoName1;
  response: NoName3;
  static: NoName6;
  views: NoName26;
  temp: NoName27;
  errorpage: NoName28;
  logger: Logger;
  regexp: NoName30;
  sqlite: SQLite;
  prettier: Prettier;
  sidebar: NoName33;
}
export interface NoName1 {
  urlencoded: Urlencoded;
}
export interface Urlencoded {
  limit: NoName2;
}
export interface NoName3 {
  header: NoName4;
  compression: NoName5;
}
export interface NoName4 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
  csp_html: ContentSecurityPolicyHTML1;
  cspro_html: ContentSecurityPolicyReportOnlyHTML;
}
export interface NoName5 {
  threshold: Threshold;
}
export interface NoName6 {
  root: NoName7;
  extensions?: NoName8;
  indexes?: NoName9;
  headers: NoName10;
  auth_basic?: BasicAuthentication;
}
export interface NoName10 {
  mime: MIME;
  cache_control?: NoName13;
  cors?: CORS;
  source_map?: SourceMap;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: NoName11;
}
export interface MIME2 {
  [k: string]: NoName12;
}
export interface NoName13 {
  development: NoName14;
  production: NoName22;
}
export interface NoName14 {
  default: NoName15;
  path?: NoName16;
  extension?: NoName19;
  [k: string]: unknown;
}
export interface NoName22 {
  default: NoName15;
  path?: NoName16;
  extension?: NoName19;
  [k: string]: unknown;
}
export interface CORS {
  directory: CORS1;
  origin: NoName23;
}
export interface SourceMap {
  extensions?: NoName24;
}
export interface NoName28 {
  path_401: FilepathFor401Unauthorized;
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
  path_500: FilepathFor500InternalServerError;
}
export interface Logger {
  path: NoName29;
}
export interface NoName30 {
  [k: string]: NoName31;
}
export interface SQLite {
  db: DBNode;
}
export interface DBNode {
  blog: Blog;
}
export interface Prettier {
  config: NoName32;
}
export interface NoName33 {
  newly: NoName34;
}
export interface NoName34 {
  maximum_number: NoName35;
}
