/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type HTTP = number;
export type StrictTransportSecurity = string;
export type ContentSecurityPolicyHTML = string;
export type ContentSecurityPolicyHTML1 = string;
export type ContentSecurityPolicyReportOnlyHTML = string;
export type Threshold = string;
export type NoName5 = string;
export type NoName6 = string[];
export type NoName7 = string[];
export type NoName9 = string[];
export type NoName10 = string[];
export type NoName12 = string;
export type NoName14 = string[];
export type NoName15 = string;
export type NoName13 = {
  paths: NoName14;
  value: NoName15;
}[];
export type NoName17 = string[];
export type NoName18 = string;
export type NoName16 = {
  extensions: NoName17;
  value: NoName18;
}[];
export type NoName19 = string[];
export type Directory = string[];
export type NoName20 = string;
export type Htpasswd = string;
export type BasicAuthentication = {
  directory: Directory;
  realm: NoName20;
  htpasswd: Htpasswd;
}[];
export type NoName21 = string;
export type NoName22 = string;
export type FilepathFor401Unauthorized = string;
export type FilepathFor403Forbidden = string;
export type FilepathFor404NotFound = string;
export type FilepathFor500InternalServerError = string;
export type NoName24 = string;
export type Blog = string;
export type APIKey = string;
export type APIKeySecret = string;
export type AccessToken = string;
export type AccessTokenSecret = string;

export interface NoName {
  port: HTTP;
  response: NoName1;
  static: NoName4;
  views: NoName21;
  temp: NoName22;
  errorpage: NoName23;
  logger: Logger;
  sqlite: SQLite;
  twitter: TwitterAPI;
}
export interface NoName1 {
  header: NoName2;
  compression: NoName3;
}
export interface NoName2 {
  hsts: StrictTransportSecurity;
  csp: ContentSecurityPolicyHTML;
  csp_html: ContentSecurityPolicyHTML1;
  cspro_html: ContentSecurityPolicyReportOnlyHTML;
}
export interface NoName3 {
  threshold: Threshold;
}
export interface NoName4 {
  root: NoName5;
  extensions?: NoName6;
  indexes?: NoName7;
  headers: NoName8;
  auth_basic?: BasicAuthentication;
}
export interface NoName8 {
  mime: MIME;
  cache_control?: NoName11;
  source_map?: SourceMap;
}
export interface MIME {
  path: MIME1;
  extension: MIME2;
}
export interface MIME1 {
  [k: string]: NoName9;
}
export interface MIME2 {
  [k: string]: NoName10;
}
export interface NoName11 {
  default: NoName12;
  path: NoName13;
  extension: NoName16;
}
export interface SourceMap {
  extensions?: NoName19;
}
export interface NoName23 {
  path_401: FilepathFor401Unauthorized;
  path_403: FilepathFor403Forbidden;
  path_404: FilepathFor404NotFound;
  path_500: FilepathFor500InternalServerError;
}
export interface Logger {
  path: NoName24;
}
export interface SQLite {
  db: DBNode;
}
export interface DBNode {
  blog: Blog;
}
export interface TwitterAPI {
  dev: NoName25;
}
export interface NoName25 {
  consumer_key: APIKey;
  consumer_secret: APIKeySecret;
  access_token: AccessToken;
  access_token_secret: AccessTokenSecret;
}
