/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName4 = number;

export interface NoName {
  view: View;
  sidebar: NoName2;
}
export interface View {
  success: NoName1;
}
export interface NoName2 {
  newly: NoName3;
}
export interface NoName3 {
  maximum_number: NoName4;
}
