/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = string;
export type NoName2 = string;
export type NoName3 = string;
export type Brotli = string;

export interface NoName {
  view: View;
  html: HTML;
}
export interface View {
  success: NoName1;
}
export interface HTML {
  directory: NoName2;
  extension: NoName3;
  brotli_extension: Brotli;
}
