/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName1 = number;
export type View = string;
export type Feed = string;

export interface NoName {
  maximum_number: NoName1;
  view_path: View;
  file_path: Feed;
}
