/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName2 = string;
export type NoName3 = string;
export type NoName4 = string;
export type NoName1 = {
  host: NoName2;
  name: NoName3;
  src: NoName4;
}[];

export interface NoName {
  anchor_host_icon: NoName1;
}
