/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type NoName = string;
/**
 * https://affiliate.amazon.co.jp/assoc_credentials/home
 */
export type NoName1 = string;
/**
 * https://affiliate.amazon.co.jp/assoc_credentials/home
 */
export type NoName2 = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/locale-reference.html
 */
export type TargetAmazonLocale = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html#host-and-region
 */
export type TheHostValueOfTheTargetLocaleToWhichYouAreSendingRequests = string;
/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html#host-and-region
 */
export type TheAWSRegionOfTheTargetLocaleToWhichYouAreSendingRequests = string;

/**
 * https://webservices.amazon.com/paapi5/documentation/common-request-parameters.html
 */
export interface PAAPI {
  partner_tag: NoName;
  access_key: NoName1;
  secret_key: NoName2;
  marketplace: TargetAmazonLocale;
  host: TheHostValueOfTheTargetLocaleToWhichYouAreSendingRequests;
  region: TheAWSRegionOfTheTargetLocaleToWhichYouAreSendingRequests;
}
