/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type APIKey = string;
export type APIKeySecret = string;
export type AccessToken = string;
export type AccessTokenSecret = string;

export interface TwitterAPI {
  production: Production;
}
export interface Production {
  consumer_key: APIKey;
  consumer_secret: APIKeySecret;
  access_token?: AccessToken;
  access_token_secret?: AccessTokenSecret;
  [k: string]: unknown;
}
