name: backend@node-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/**/*.test.js'
      - 'packages/backend/node/@types/*.d.ts'
      - 'packages/backend/node/src/**/*.ts'
      - 'packages/backend/.eslintrc.json'
  push:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/**/*.test.js'
      - 'packages/backend/node/@types/*.d.ts'
      - 'packages/backend/node/src/**/*.ts'
      - 'packages/backend/.eslintrc.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint -w '@blog.w0s.jp/backend'
