name: backend@node-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/*.test.js'
      - 'packages/backend/node/src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/*.test.js'
      - 'packages/backend/node/src/**/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build -w '@blog.w0s.jp/util'
      - run: npm run test -w '@blog.w0s.jp/backend'
