name: backend@errorpage-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'backend/errorpage/*.html'
      - 'markuplint.config.js'
  push:
    branches:
      - main
    paths:
      - 'backend/errorpage/*.html'
      - 'markuplint.config.js'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run errorpage-lint -w '@blog.w0s.jp/backend'
