name: backend@node-test
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/*.test.js'
      - 'packages/backend/node/src/**/*.ts'
  push:
    branches:
      - main
    paths:
      - 'packages/backend/node/__tests__/*.test.js'
      - 'packages/backend/node/src/**/*.ts'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm test -w '@blog.w0s.jp/backend'
