name: frontend@node-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/build/*.js'
      - 'frontend/.eslintrc.json'
  push:
    branches:
      - main
    paths:
      - 'frontend/build/*.js'
      - 'frontend/.eslintrc.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run node-lint -w '@blog.w0s.jp/frontend'
