name: CSS files

on:
  pull_request:
    paths:
      - 'frontend/style/**/*.css'
      - 'frontend/stylelint.config.js'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run css-lint -w '@blog.w0s.jp/frontend'
