name: CSS files

on:
  pull_request:
    paths:
      - 'frontend/style/**/*.css'
      - 'frontend/package.json'
      - 'frontend/stylelint.config.js'
      - 'package.json'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '24'
      - run: npm ci
      - run: npm run css-lint -w '@blog.w0s.jp/frontend'
