name: frontend@css-lint
on:
  pull_request:
    branches:
      - main
    paths:
      - 'packages/frontend/style/**/*.css'
      - 'packages/frontend/.stylelintrc.json'
  push:
    branches:
      - main
    paths:
      - 'packages/frontend/style/**/*.css'
      - 'packages/frontend/.stylelintrc.json'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - run: npm ci
      - run: npm run css-lint -w '@blog.w0s.jp/frontend'
