name: hono (Backend)

on:
  pull_request:
    paths:
      - 'hono/**'
      - 'package.json'
  workflow_dispatch:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Enable pnpm
        run: corepack enable pnpm

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: '.node-version'
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm i --frozen-lockfile

      - name: Run build (media)
        run: pnpm -F media build

      - name: Run build (remark)
        run: pnpm -F remark build

      - name: Run lint
        run: pnpm -F hono lint
