name: html-lint-ejs
on:
  pull_request:
    branches:
      - main
    paths:
      - 'views/*.ejs'
      - 'views/_include/*.ejs'
      - '.markuplintrc'
  push:
    branches:
      - main
    paths:
      - 'views/*.ejs'
      - 'views/_include/*.ejs'
      - '.markuplintrc'
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm ci
      - run: npm run html-lint-ejs
