name: node-lint
on:
  push:
    branches: 
      - main
    paths:
      - 'node/src/**/*.ts'
      - 'node/@types/*.d.ts'
      - '.eslintrc.json'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: npm run node-lint
