name: YAML files

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v5
      - name: Run actionlint
        uses: docker://rhysd/actionlint:latest
        with:
          args: -color
